name = "PGFPlots"
uuid = "3b7a836e-365b-5785-a47d-02c71176b4aa"
repo = "https://github.com/JuliaTeX/PGFPlots.jl.git"
version = "3.4.6"

[deps]
ColorBrewer = "a2cac450-b92f-5266-8821-25eda20663c8"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Contour = "d38c429a-6771-53c6-b99e-75d170b6e991"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Discretizers = "6e83dbb3-75ca-525b-8ae2-3751f0dd50b4"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1" # seems to be needed for Julia 1.0
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TikzPictures = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"

[compat]
ColorBrewer = "0.4"
ColorSchemes = "3.9, 3.10, 3.11, 3.12"
Colors = "0.12"
Contour = "0.5, 0.6"
Discretizers = "3.2"
DataFrames = "0.21, 0.22, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6"
Images = "0.22, 0.23, 0.24, 0.25, 0.26"
ImageMagick = "0.7.3, 1"
Requires = "1.0, 1.1, 1.2, 1.3"
StatsBase = "0.33, 0.34"
TikzPictures = "3.1, 3.2, 3.3, 3.4, 3.5"
julia = "1"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
NBInclude = "0db19996-df87-5ea3-a455-e3a50d440464"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["NBInclude", "DataFrames", "Random", "Test"]
